pipeline:
  name: mywebapp-java-ci
  identifier: mywebappjavaci
  projectIdentifier: mywebappnow
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Compile
                  identifier: Maven_Compile
                  spec:
                    shell: Sh
                    command: mvn compile
              - step:
                  type: Run
                  name: Maven Test
                  identifier: Maven_Test
                  spec:
                    shell: Sh
                    command: mvn test
              - step:
                  type: Run
                  name: Maven package
                  identifier: Maven_package
                  spec:
                    shell: Sh
                    command: mvn package
              - step:
                  type: Run
                  name: Run_4
                  identifier: Run_4
                  spec:
                    shell: Sh
                    command: docker build -t webappv1 .
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhubconnector
                    repo: afzalmemon7/harness-demo
                    tags:
                      - webappv1
    - stage:
        name: Servicenow Create Change
        identifier: Servicenow_Create_Change
        tags: {}
        template:
          templateRef: CreateServiceNowChange
          versionLabel: "1.0"
  properties:
    ci:
      codebase:
        connectorRef: githubconnectorformywebapp
        repoName: my-java-webapp
        build: <+input>
        sparseCheckout: []
